# Generated by Django 2.1.4 on 2018-12-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_field',
            name='info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='field',
        ),
        migrations.AddField(
            model_name='contact',
            name='field',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.Info_field'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='info_field',
            table='Info_field',
        ),
    ]
