# Generated by Django 2.1.4 on 2018-12-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20181208_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_field',
            name='types_of_fields',
            field=models.CharField(choices=[('email', 'E-mail'), ('phone', 'Telefone'), ('cell', 'Celular')], default='cell', max_length=5),
        ),
    ]
