# Generated by Django 2.1.4 on 2018-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20181208_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='field',
        ),
        migrations.AddField(
            model_name='contact',
            name='cell',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Info_field',
        ),
    ]
