# Generated by Django 2.1.4 on 2018-12-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(height_field='height', max_length=200, upload_to='uploads/', width_field='width'),
        ),
    ]
