# Generated by Django 2.1.4 on 2018-12-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20181209_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(height_field='height', max_length=200, upload_to='contacts/static/uploads', width_field='width'),
        ),
    ]
