# Generated by Django 2.1.4 on 2018-12-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20181210_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', max_length=200, null=True, upload_to='media/contacts/static/uploads', width_field='width'),
        ),
    ]
