# Generated by Django 2.1.4 on 2018-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20181211_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', max_length=200, null=True, upload_to='media/', width_field='width'),
        ),
    ]
